
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 22/4/2022 - 03:14 p. m.
// This is a partial class file. The other one is ContactosOrigenGateway.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using crmRules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Web;




namespace crmRules.Gateways
{

    public partial class ContactosOrigenGateway : BaseGateway<ContactosOrigenObject, ContactosOrigenObjectList>, IGenericGateway
    {

        #region "Singleton"

        static ContactosOrigenGateway _instance;

        private ContactosOrigenGateway()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        
        
        public static ContactosOrigenGateway Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new ContactosOrigenGateway();
                else {
                    ContactosOrigenGateway inst = HttpContext.Current.Items["crmRules.ContactosOrigenGatewaySingleton"] as ContactosOrigenGateway;
                    if (inst == null) {
                        inst = new ContactosOrigenGateway();
                        HttpContext.Current.Items.Add("crmRules.ContactosOrigenGatewaySingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }

        #endregion

        /// <summary>
        /// Return the mapped table name
        /// </summary>
        protected override string TableName
        {
            get { return "ContactosOrigen"; }
        }

        protected override string RuleName
        {
            get {return typeof(ContactosOrigenGateway).FullName;}
        }


        

        /// <summary>
        /// Assign properties values based on DataReader
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, ContactosOrigenObject entity)
        {
            
            IMappeableContactosOrigenObject ContactosOrigen = (IMappeableContactosOrigenObject)entity;
            ContactosOrigen.HydrateFields(
            reader.GetInt32(0),
reader.GetString(1),
reader.GetBoolean(2));
            ((IObject)entity).State = ObjectState.Restored;
        }

        /// <summary>
        /// Get field values to call insertion stored procedure
        /// </summary>
        protected override object[] GetFieldsForInsert(ContactosOrigenObject entity)
        {

            IMappeableContactosOrigenObject ContactosOrigen = (IMappeableContactosOrigenObject)entity;
            return ContactosOrigen.GetFieldsForInsert();
        }

        /// <summary>
        /// Get field values to call update stored procedure
        /// </summary>
        protected override object[] GetFieldsForUpdate(ContactosOrigenObject entity)
        {

            IMappeableContactosOrigenObject ContactosOrigen = (IMappeableContactosOrigenObject)entity;
            return ContactosOrigen.GetFieldsForUpdate();
        }

        /// <summary>
        /// Get field values to call deletion stored procedure
        /// </summary>
        protected override object[] GetFieldsForDelete(ContactosOrigenObject entity)
        {

            IMappeableContactosOrigenObject ContactosOrigen = (IMappeableContactosOrigenObject)entity;
            return ContactosOrigen.GetFieldsForDelete();
        }

        /// <summary>
        /// Raised after insert and update. Update properties from Output parameters
        /// </summary>
        protected override void UpdateObjectFromOutputParams(ContactosOrigenObject row, object[] parameters)
        {
            ((IMappeableContactosOrigenObject) row).UpdateObjectFromOutputParams(parameters);
            ((IObject)row).State = ObjectState.Restored;
        }

        /// <summary>
        /// StoredProceduresPrefix, for example: coop_
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "coop_";
        }


        /// <summary>
        /// Get a ContactosOrigenObject by execute a SQL Query Text
        /// </summary>
        public ContactosOrigenObject GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a ContactosOrigenObjectList by execute a SQL Query Text
        /// </summary>
        public ContactosOrigenObjectList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// Get a ContactosOrigenObject by calling a Stored Procedure
        /// </summary>
        public ContactosOrigenObject GetOne(System.Int32 IdOrigen)
        {
            return base.GetOne(new ContactosOrigenObject(IdOrigen));
        }


        // GetBy Objects and Params
            


        

        

        /// <summary>
        /// Delete ContactosOrigen
        /// </summary>
        public void Delete(System.Int32 IdOrigen)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "ContactosOrigen_Delete", IdOrigen);
        }

        /// <summary>
        /// Delete ContactosOrigen
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 IdOrigen)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "ContactosOrigen_Delete", IdOrigen);
        }

            

        


        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }

}








