
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 19/4/2022 - 03:39 p. m.
// This is a partial class file. The other one is ContactosTipoUsuarioGateway.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using crmRules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Web;




namespace crmRules.Gateways
{

    public partial class ContactosTipoUsuarioGateway : BaseGateway<ContactosTipoUsuarioObject, ContactosTipoUsuarioObjectList>, IGenericGateway
    {

        #region "Singleton"

        static ContactosTipoUsuarioGateway _instance;

        private ContactosTipoUsuarioGateway()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        
        
        public static ContactosTipoUsuarioGateway Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new ContactosTipoUsuarioGateway();
                else {
                    ContactosTipoUsuarioGateway inst = HttpContext.Current.Items["crmRules.ContactosTipoUsuarioGatewaySingleton"] as ContactosTipoUsuarioGateway;
                    if (inst == null) {
                        inst = new ContactosTipoUsuarioGateway();
                        HttpContext.Current.Items.Add("crmRules.ContactosTipoUsuarioGatewaySingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }

        #endregion

        /// <summary>
        /// Return the mapped table name
        /// </summary>
        protected override string TableName
        {
            get { return "ContactosTipoUsuario"; }
        }

        protected override string RuleName
        {
            get {return typeof(ContactosTipoUsuarioGateway).FullName;}
        }


        

        /// <summary>
        /// Assign properties values based on DataReader
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, ContactosTipoUsuarioObject entity)
        {
            System.Byte[] _Nombre = new System.Byte[50]; if (!reader.IsDBNull(1)) _Nombre = reader.GetValue(1) as System.Byte[];

            IMappeableContactosTipoUsuarioObject ContactosTipoUsuario = (IMappeableContactosTipoUsuarioObject)entity;
            ContactosTipoUsuario.HydrateFields(
            reader.GetInt32(0),
_Nombre,
reader.GetBoolean(2));
            ((IObject)entity).State = ObjectState.Restored;
        }

        /// <summary>
        /// Get field values to call insertion stored procedure
        /// </summary>
        protected override object[] GetFieldsForInsert(ContactosTipoUsuarioObject entity)
        {

            IMappeableContactosTipoUsuarioObject ContactosTipoUsuario = (IMappeableContactosTipoUsuarioObject)entity;
            return ContactosTipoUsuario.GetFieldsForInsert();
        }

        /// <summary>
        /// Get field values to call update stored procedure
        /// </summary>
        protected override object[] GetFieldsForUpdate(ContactosTipoUsuarioObject entity)
        {

            IMappeableContactosTipoUsuarioObject ContactosTipoUsuario = (IMappeableContactosTipoUsuarioObject)entity;
            return ContactosTipoUsuario.GetFieldsForUpdate();
        }

        /// <summary>
        /// Get field values to call deletion stored procedure
        /// </summary>
        protected override object[] GetFieldsForDelete(ContactosTipoUsuarioObject entity)
        {

            IMappeableContactosTipoUsuarioObject ContactosTipoUsuario = (IMappeableContactosTipoUsuarioObject)entity;
            return ContactosTipoUsuario.GetFieldsForDelete();
        }

        /// <summary>
        /// Raised after insert and update. Update properties from Output parameters
        /// </summary>
        protected override void UpdateObjectFromOutputParams(ContactosTipoUsuarioObject row, object[] parameters)
        {
            ((IMappeableContactosTipoUsuarioObject) row).UpdateObjectFromOutputParams(parameters);
            ((IObject)row).State = ObjectState.Restored;
        }

        /// <summary>
        /// StoredProceduresPrefix, for example: coop_
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "coop_";
        }


        /// <summary>
        /// Get a ContactosTipoUsuarioObject by execute a SQL Query Text
        /// </summary>
        public ContactosTipoUsuarioObject GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a ContactosTipoUsuarioObjectList by execute a SQL Query Text
        /// </summary>
        public ContactosTipoUsuarioObjectList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// Get a ContactosTipoUsuarioObject by calling a Stored Procedure
        /// </summary>
        public ContactosTipoUsuarioObject GetOne(System.Int32 IdTipoUsuarioContacto)
        {
            return base.GetOne(new ContactosTipoUsuarioObject(IdTipoUsuarioContacto));
        }


        // GetBy Objects and Params
            


        

        

        /// <summary>
        /// Delete ContactosTipoUsuario
        /// </summary>
        public void Delete(System.Int32 IdTipoUsuarioContacto)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "ContactosTipoUsuario_Delete", IdTipoUsuarioContacto);
        }

        /// <summary>
        /// Delete ContactosTipoUsuario
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 IdTipoUsuarioContacto)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "ContactosTipoUsuario_Delete", IdTipoUsuarioContacto);
        }

            

        


        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }

}








