
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 18/5/2022 - 11:33 a. m.
// This is a partial class file. The other one is ContactosEstadosGateway.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using crmRules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Web;




namespace crmRules.Gateways
{

    public partial class ContactosEstadosGateway : BaseGateway<ContactosEstadosObject, ContactosEstadosObjectList>, IGenericGateway
    {

        #region "Singleton"

        static ContactosEstadosGateway _instance;

        private ContactosEstadosGateway()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        
        
        public static ContactosEstadosGateway Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new ContactosEstadosGateway();
                else {
                    ContactosEstadosGateway inst = HttpContext.Current.Items["crmRules.ContactosEstadosGatewaySingleton"] as ContactosEstadosGateway;
                    if (inst == null) {
                        inst = new ContactosEstadosGateway();
                        HttpContext.Current.Items.Add("crmRules.ContactosEstadosGatewaySingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }

        #endregion

        /// <summary>
        /// Return the mapped table name
        /// </summary>
        protected override string TableName
        {
            get { return "ContactosEstados"; }
        }

        protected override string RuleName
        {
            get {return typeof(ContactosEstadosGateway).FullName;}
        }


        

        /// <summary>
        /// Assign properties values based on DataReader
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, ContactosEstadosObject entity)
        {
            
            IMappeableContactosEstadosObject ContactosEstados = (IMappeableContactosEstadosObject)entity;
            ContactosEstados.HydrateFields(
            reader.GetInt32(0),
reader.GetString(1),
reader.GetInt32(2),
reader.GetBoolean(3));
            ((IObject)entity).State = ObjectState.Restored;
        }

        /// <summary>
        /// Get field values to call insertion stored procedure
        /// </summary>
        protected override object[] GetFieldsForInsert(ContactosEstadosObject entity)
        {

            IMappeableContactosEstadosObject ContactosEstados = (IMappeableContactosEstadosObject)entity;
            return ContactosEstados.GetFieldsForInsert();
        }

        /// <summary>
        /// Get field values to call update stored procedure
        /// </summary>
        protected override object[] GetFieldsForUpdate(ContactosEstadosObject entity)
        {

            IMappeableContactosEstadosObject ContactosEstados = (IMappeableContactosEstadosObject)entity;
            return ContactosEstados.GetFieldsForUpdate();
        }

        /// <summary>
        /// Get field values to call deletion stored procedure
        /// </summary>
        protected override object[] GetFieldsForDelete(ContactosEstadosObject entity)
        {

            IMappeableContactosEstadosObject ContactosEstados = (IMappeableContactosEstadosObject)entity;
            return ContactosEstados.GetFieldsForDelete();
        }

        /// <summary>
        /// Raised after insert and update. Update properties from Output parameters
        /// </summary>
        protected override void UpdateObjectFromOutputParams(ContactosEstadosObject row, object[] parameters)
        {
            ((IMappeableContactosEstadosObject) row).UpdateObjectFromOutputParams(parameters);
            ((IObject)row).State = ObjectState.Restored;
        }

        /// <summary>
        /// StoredProceduresPrefix, for example: coop_
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "coop_";
        }


        /// <summary>
        /// Get a ContactosEstadosObject by execute a SQL Query Text
        /// </summary>
        public ContactosEstadosObject GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a ContactosEstadosObjectList by execute a SQL Query Text
        /// </summary>
        public ContactosEstadosObjectList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// Get a ContactosEstadosObject by calling a Stored Procedure
        /// </summary>
        public ContactosEstadosObject GetOne(System.Int32 IdEstadoContacto)
        {
            return base.GetOne(new ContactosEstadosObject(IdEstadoContacto));
        }


        // GetBy Objects and Params
            


        

        

        /// <summary>
        /// Delete ContactosEstados
        /// </summary>
        public void Delete(System.Int32 IdEstadoContacto)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "ContactosEstados_Delete", IdEstadoContacto);
        }

        /// <summary>
        /// Delete ContactosEstados
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 IdEstadoContacto)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "ContactosEstados_Delete", IdEstadoContacto);
        }

            

        


        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }

}








