
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 13/5/2022 - 02:18 p. m.
// This is a partial class file. The other one is PlantillasMailGateway.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using crmRules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Web;




namespace crmRules.Gateways
{

    public partial class PlantillasMailGateway : BaseGateway<PlantillasMailObject, PlantillasMailObjectList>, IGenericGateway
    {

        #region "Singleton"

        static PlantillasMailGateway _instance;

        private PlantillasMailGateway()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        
        
        public static PlantillasMailGateway Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new PlantillasMailGateway();
                else {
                    PlantillasMailGateway inst = HttpContext.Current.Items["crmRules.PlantillasMailGatewaySingleton"] as PlantillasMailGateway;
                    if (inst == null) {
                        inst = new PlantillasMailGateway();
                        HttpContext.Current.Items.Add("crmRules.PlantillasMailGatewaySingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }

        #endregion

        /// <summary>
        /// Return the mapped table name
        /// </summary>
        protected override string TableName
        {
            get { return "PlantillasMail"; }
        }

        protected override string RuleName
        {
            get {return typeof(PlantillasMailGateway).FullName;}
        }


        

        /// <summary>
        /// Assign properties values based on DataReader
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, PlantillasMailObject entity)
        {
            
            IMappeablePlantillasMailObject PlantillasMail = (IMappeablePlantillasMailObject)entity;
            PlantillasMail.HydrateFields(
            reader.GetInt32(0),
reader.GetString(1),
reader.GetString(2),
reader.GetBoolean(3));
            ((IObject)entity).State = ObjectState.Restored;
        }

        /// <summary>
        /// Get field values to call insertion stored procedure
        /// </summary>
        protected override object[] GetFieldsForInsert(PlantillasMailObject entity)
        {

            IMappeablePlantillasMailObject PlantillasMail = (IMappeablePlantillasMailObject)entity;
            return PlantillasMail.GetFieldsForInsert();
        }

        /// <summary>
        /// Get field values to call update stored procedure
        /// </summary>
        protected override object[] GetFieldsForUpdate(PlantillasMailObject entity)
        {

            IMappeablePlantillasMailObject PlantillasMail = (IMappeablePlantillasMailObject)entity;
            return PlantillasMail.GetFieldsForUpdate();
        }

        /// <summary>
        /// Get field values to call deletion stored procedure
        /// </summary>
        protected override object[] GetFieldsForDelete(PlantillasMailObject entity)
        {

            IMappeablePlantillasMailObject PlantillasMail = (IMappeablePlantillasMailObject)entity;
            return PlantillasMail.GetFieldsForDelete();
        }

        /// <summary>
        /// Raised after insert and update. Update properties from Output parameters
        /// </summary>
        protected override void UpdateObjectFromOutputParams(PlantillasMailObject row, object[] parameters)
        {
            ((IMappeablePlantillasMailObject) row).UpdateObjectFromOutputParams(parameters);
            ((IObject)row).State = ObjectState.Restored;
        }

        /// <summary>
        /// StoredProceduresPrefix, for example: coop_
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "coop_";
        }


        /// <summary>
        /// Get a PlantillasMailObject by execute a SQL Query Text
        /// </summary>
        public PlantillasMailObject GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a PlantillasMailObjectList by execute a SQL Query Text
        /// </summary>
        public PlantillasMailObjectList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// Get a PlantillasMailObject by calling a Stored Procedure
        /// </summary>
        public PlantillasMailObject GetOne(System.Int32 IdPlantillaEmail)
        {
            return base.GetOne(new PlantillasMailObject(IdPlantillaEmail));
        }


        // GetBy Objects and Params
            


        

        

        /// <summary>
        /// Delete PlantillasMail
        /// </summary>
        public void Delete(System.Int32 IdPlantillaEmail)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "PlantillasMail_Delete", IdPlantillaEmail);
        }

        /// <summary>
        /// Delete PlantillasMail
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 IdPlantillaEmail)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "PlantillasMail_Delete", IdPlantillaEmail);
        }

            

        


        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }

}








