
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 18/5/2022 - 11:33 a. m.
// This is a partial class file. The other one is ContactosTipoAccionesEntity.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using crmRules.Objects;



using Cooperator.Framework.Core;
using Cooperator.Framework.Core.LazyLoad;
using System;

namespace crmRules.Entities
{

    /// <summary>
    /// 
    /// </summary>
    public partial class ContactosTipoAcciones : Objects.ContactosTipoAccionesObject, IMappeableContactosTipoAcciones, IEquatable<ContactosTipoAcciones>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public ContactosTipoAcciones()
            :base()
        {
            
        }

        /// <summary>
        /// 
        /// </summary>
        public ContactosTipoAcciones(
			System.Int32 IdTipoAccionContacto)
            : base()
        {

			_IdTipoAccionContacto = IdTipoAccionContacto;

            
            Initialized();
        }

        

        /// <summary>
        /// 
        /// </summary>
        public ContactosTipoAcciones(
			System.Int32 IdTipoAccionContacto,
			System.String TipoAccion,
			System.Boolean Activa)
            : base()
        {

			_IdTipoAccionContacto = IdTipoAccionContacto;
			_TipoAccion = TipoAccion;
			_Activa = Activa;

            
            Initialized();
        }
        
        #endregion

        #region "Fields"

        
        #endregion

        #region "Properties"
        
        #endregion

        /// <summary>
        /// Returns de original value of entity since was created or restored.
        /// </summary>
        public new ContactosTipoAcciones OriginalValue()
        {
            return (ContactosTipoAcciones)base.OriginalValue();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            ContactosTipoAcciones newObject;            
            

            newObject = (ContactosTipoAcciones)this.MemberwiseClone();
            // Entities
            
            // Colections
            
            // OriginalValue
            ContactosTipoAcciones newOriginalValue;
            if (base._OriginalValue != null)
            {
                newOriginalValue = (ContactosTipoAcciones)this.OriginalValue().MemberwiseClone();
                // Entities
                
                // Colections
                            
                newObject._OriginalValue = newOriginalValue;

            }
            return newObject;            
        }



        /// <summary>
        /// 
        /// </summary>
        void IMappeableContactosTipoAcciones.CompleteEntity()
        {
        
        }
        

        /// <summary>
        /// 
        /// </summary>
        void IMappeableContactosTipoAcciones.SetFKValuesForChilds(ContactosTipoAcciones entity)
        {
                
        }

        /// <summary>
        /// 
        /// </summary>
        public bool Equals(ContactosTipoAcciones other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        } 

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableContactosTipoAcciones
    {
        /// <summary>
        /// 
        /// </summary>
        void CompleteEntity();
        
        /// <summary>
        /// 
        /// </summary>
        void SetFKValuesForChilds(ContactosTipoAcciones entity);
    }

        /// <summary>
        /// 
        /// </summary>
    public partial class ContactosTipoAccionesList : ObjectList<ContactosTipoAcciones>
    {
    }
}
namespace crmRules.Views
{
        /// <summary>
        /// 
        /// </summary>
    public partial class ContactosTipoAccionesListView
        : ObjectListView<Entities.ContactosTipoAcciones>
    {
        /// <summary>
        /// 
        /// </summary>
        public ContactosTipoAccionesListView(Entities.ContactosTipoAccionesList list): base(list)
        {
        }
    }
}


