
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 13/5/2022 - 02:18 p. m.
// This is a partial class file. The other one is ContactoHistorialAciconesObject.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using Cooperator.Framework.Core;
using System;

namespace crmRules.Objects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ContactoHistorialAciconesObject : BaseObject, IMappeableContactoHistorialAciconesObject, IUniqueIdentifiable, IEquatable<ContactoHistorialAciconesObject>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public ContactoHistorialAciconesObject(): base()
        {

			_IdHistorialAcciones =  ValuesGenerator.GetInt32;

        }

        /// <summary>
        /// 
        /// </summary>
        public ContactoHistorialAciconesObject(
			System.Int32 IdHistorialAcciones): base()
        {

			_IdHistorialAcciones = IdHistorialAcciones;

            Initialized();
        }

        
        /// <summary>
        /// 
        /// </summary>
        public ContactoHistorialAciconesObject(
			System.Int32 IdHistorialAcciones,
			System.Int32 IdTipoAccion,
			System.String Accion,
			System.Int32 IdContacto,
			System.Int32 IdUsuario,
			System.DateTime Fecha,
			System.Boolean Activo): base()
        {

			_IdHistorialAcciones = IdHistorialAcciones;
			_IdTipoAccion = IdTipoAccion;
			_Accion = Accion;
			_IdContacto = IdContacto;
			_IdUsuario = IdUsuario;
			_Fecha = Fecha;
			_Activo = Activo;

            Initialized();
        }
        

        #endregion

        #region "Events"
        
        
        #endregion

        #region "Fields"

            /// <summary>
/// 
/// </summary>
protected System.Int32 _IdHistorialAcciones;
/// <summary>
/// 
/// </summary>
protected System.Int32 _IdTipoAccion;
/// <summary>
/// 
/// </summary>
protected System.String _Accion;
/// <summary>
/// 
/// </summary>
protected System.Int32 _IdContacto;
/// <summary>
/// 
/// </summary>
protected System.Int32 _IdUsuario;
/// <summary>
/// 
/// </summary>
protected System.DateTime _Fecha;
/// <summary>
/// 
/// </summary>
protected System.Boolean _Activo;

        #endregion

        #region "Properties"
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 IdHistorialAcciones
        {
            get
            {
                return _IdHistorialAcciones;
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 IdTipoAccion
        {
            get
            {
                return _IdTipoAccion;
            }
            
            set
            {
                base.PropertyModified();
                _IdTipoAccion = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Accion
        {
            get
            {
                return _Accion;
            }
            
            set
            {
                base.PropertyModified();
                _Accion = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 IdContacto
        {
            get
            {
                return _IdContacto;
            }
            
            set
            {
                base.PropertyModified();
                _IdContacto = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            
            set
            {
                base.PropertyModified();
                _IdUsuario = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            
            set
            {
                base.PropertyModified();
                _Fecha = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Boolean Activo
        {
            get
            {
                return _Activo;
            }
            
            set
            {
                base.PropertyModified();
                _Activo = value;
                
            }
            
        }
        
        #endregion

        
            
                
        /// <summary>
        /// 
        /// </summary>
        protected override void SetOriginalValue()
        {
            base._OriginalValue = (IObject) this.MemberwiseClone();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            ContactoHistorialAciconesObject newObject;
            ContactoHistorialAciconesObject newOriginalValue;

            newObject = (ContactoHistorialAciconesObject) this.MemberwiseClone();
            if (base._OriginalValue != null)
            {
                newOriginalValue = (ContactoHistorialAciconesObject)this.OriginalValue().MemberwiseClone();
                newObject._OriginalValue = newOriginalValue;
            }
            return newObject;
        }


        /// <summary>
        /// Returns de original value of object since was created or restored.
        /// </summary>
        public new ContactoHistorialAciconesObject OriginalValue()
        {
            return (ContactoHistorialAciconesObject)base.OriginalValue();
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableContactoHistorialAciconesObject.HydrateFields(
			System.Int32 IdHistorialAcciones,
			System.Int32 IdTipoAccion,
			System.String Accion,
			System.Int32 IdContacto,
			System.Int32 IdUsuario,
			System.DateTime Fecha,
			System.Boolean Activo)
        {
        _IdHistorialAcciones = IdHistorialAcciones;
_IdTipoAccion = IdTipoAccion;
_Accion = Accion;
_IdContacto = IdContacto;
_IdUsuario = IdUsuario;
_Fecha = Fecha;
_Activo = Activo;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableContactoHistorialAciconesObject.GetFieldsForInsert()
        {
            object[] _myArray = new object[7];
            _myArray[0] = _IdHistorialAcciones;
_myArray[1] = _IdTipoAccion;
_myArray[2] = _Accion;
_myArray[3] = _IdContacto;
_myArray[4] = _IdUsuario;
_myArray[5] = _Fecha;
_myArray[6] = _Activo;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableContactoHistorialAciconesObject.GetFieldsForUpdate()
        {
            
            object[] _myArray = new object[7];
            _myArray[0] = _IdHistorialAcciones;
_myArray[1] = _IdTipoAccion;
_myArray[2] = _Accion;
_myArray[3] = _IdContacto;
_myArray[4] = _IdUsuario;
_myArray[5] = _Fecha;
_myArray[6] = _Activo;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableContactoHistorialAciconesObject.GetFieldsForDelete()
        {
            
            object[] _myArray = new object[1];
            _myArray[0] = _IdHistorialAcciones;

            return _myArray;
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableContactoHistorialAciconesObject.UpdateObjectFromOutputParams(object[] parameters){
            // Update properties from Output parameters
            _IdHistorialAcciones = (System.Int32) parameters[0];

        }


        /// <summary>
        /// 
        /// </summary>
        object[] IUniqueIdentifiable.Identifier()
        {
            ContactoHistorialAciconesObject o = null;
            if (ObjectStateHelper.IsModified(this))
                o = this.OriginalValue();
            else
                o = this;

            return new object[]
            {o.IdHistorialAcciones};
        }


        /// <summary>
        /// 
        /// </summary>
        public bool Equals(ContactoHistorialAciconesObject other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        }

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableContactoHistorialAciconesObject
    {
        /// <summary>
        /// 
        /// </summary>
        void HydrateFields(System.Int32 IdHistorialAcciones, 
			System.Int32 IdTipoAccion, 
			System.String Accion, 
			System.Int32 IdContacto, 
			System.Int32 IdUsuario, 
			System.DateTime Fecha, 
			System.Boolean Activo);

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForInsert();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForUpdate();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForDelete();

        /// <summary>
        /// 
        /// </summary>
        void UpdateObjectFromOutputParams(object[] parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    public partial class ContactoHistorialAciconesObjectList : ObjectList<ContactoHistorialAciconesObject>
    {
    }
}

namespace crmRules.Views
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ContactoHistorialAciconesObjectListView
        : ObjectListView<Objects.ContactoHistorialAciconesObject>
    {
        /// <summary>
        /// 
        /// </summary>
        public ContactoHistorialAciconesObjectListView(Objects.ContactoHistorialAciconesObjectList list): base(list)
        {
        }
    }
}


