
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 18/5/2022 - 11:33 a. m.
// This is a partial class file. The other one is ContactosEstadosObject.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using Cooperator.Framework.Core;
using System;

namespace crmRules.Objects
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ContactosEstadosObject : BaseObject, IMappeableContactosEstadosObject, IUniqueIdentifiable, IEquatable<ContactosEstadosObject>, ICloneable
    {

        #region "Ctor"

        /// <summary>
        /// 
        /// </summary>
        public ContactosEstadosObject(): base()
        {

			_IdEstadoContacto =  ValuesGenerator.GetInt32;

        }

        /// <summary>
        /// 
        /// </summary>
        public ContactosEstadosObject(
			System.Int32 IdEstadoContacto): base()
        {

			_IdEstadoContacto = IdEstadoContacto;

            Initialized();
        }

        
        /// <summary>
        /// 
        /// </summary>
        public ContactosEstadosObject(
			System.Int32 IdEstadoContacto,
			System.String Nombre,
			System.Int32 Orden,
			System.Boolean Activo): base()
        {

			_IdEstadoContacto = IdEstadoContacto;
			_Nombre = Nombre;
			_Orden = Orden;
			_Activo = Activo;

            Initialized();
        }
        

        #endregion

        #region "Events"
        
        
        #endregion

        #region "Fields"

            /// <summary>
/// 
/// </summary>
protected System.Int32 _IdEstadoContacto;
/// <summary>
/// 
/// </summary>
protected System.String _Nombre;
/// <summary>
/// 
/// </summary>
protected System.Int32 _Orden;
/// <summary>
/// 
/// </summary>
protected System.Boolean _Activo;

        #endregion

        #region "Properties"
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 IdEstadoContacto
        {
            get
            {
                return _IdEstadoContacto;
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            
            set
            {
                base.PropertyModified();
                _Nombre = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Int32 Orden
        {
            get
            {
                return _Orden;
            }
            
            set
            {
                base.PropertyModified();
                _Orden = value;
                
            }
            
        }
        
        /// <summary>
        /// 
        /// </summary>
        public virtual System.Boolean Activo
        {
            get
            {
                return _Activo;
            }
            
            set
            {
                base.PropertyModified();
                _Activo = value;
                
            }
            
        }
        
        #endregion

        
            
                
        /// <summary>
        /// 
        /// </summary>
        protected override void SetOriginalValue()
        {
            base._OriginalValue = (IObject) this.MemberwiseClone();
        }

        /// <summary>
        /// 
        /// </summary>
        object ICloneable.Clone()
        {
            ContactosEstadosObject newObject;
            ContactosEstadosObject newOriginalValue;

            newObject = (ContactosEstadosObject) this.MemberwiseClone();
            if (base._OriginalValue != null)
            {
                newOriginalValue = (ContactosEstadosObject)this.OriginalValue().MemberwiseClone();
                newObject._OriginalValue = newOriginalValue;
            }
            return newObject;
        }


        /// <summary>
        /// Returns de original value of object since was created or restored.
        /// </summary>
        public new ContactosEstadosObject OriginalValue()
        {
            return (ContactosEstadosObject)base.OriginalValue();
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableContactosEstadosObject.HydrateFields(
			System.Int32 IdEstadoContacto,
			System.String Nombre,
			System.Int32 Orden,
			System.Boolean Activo)
        {
        _IdEstadoContacto = IdEstadoContacto;
_Nombre = Nombre;
_Orden = Orden;
_Activo = Activo;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableContactosEstadosObject.GetFieldsForInsert()
        {
            object[] _myArray = new object[4];
            _myArray[0] = _IdEstadoContacto;
_myArray[1] = _Nombre;
_myArray[2] = _Orden;
_myArray[3] = _Activo;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableContactosEstadosObject.GetFieldsForUpdate()
        {
            
            object[] _myArray = new object[4];
            _myArray[0] = _IdEstadoContacto;
_myArray[1] = _Nombre;
_myArray[2] = _Orden;
_myArray[3] = _Activo;

            return _myArray;
        }

        /// <summary>
        /// 
        /// </summary>
        object[] IMappeableContactosEstadosObject.GetFieldsForDelete()
        {
            
            object[] _myArray = new object[1];
            _myArray[0] = _IdEstadoContacto;

            return _myArray;
        }


        /// <summary>
        /// 
        /// </summary>
        void IMappeableContactosEstadosObject.UpdateObjectFromOutputParams(object[] parameters){
            // Update properties from Output parameters
            _IdEstadoContacto = (System.Int32) parameters[0];

        }


        /// <summary>
        /// 
        /// </summary>
        object[] IUniqueIdentifiable.Identifier()
        {
            ContactosEstadosObject o = null;
            if (ObjectStateHelper.IsModified(this))
                o = this.OriginalValue();
            else
                o = this;

            return new object[]
            {o.IdEstadoContacto};
        }


        /// <summary>
        /// 
        /// </summary>
        public bool Equals(ContactosEstadosObject other)
        {
            return UniqueIdentifierHelper.IsSameObject((IUniqueIdentifiable)this, (IUniqueIdentifiable)other);
        }

    }

    /// <summary>
    /// 
    /// </summary>
    public interface IMappeableContactosEstadosObject
    {
        /// <summary>
        /// 
        /// </summary>
        void HydrateFields(System.Int32 IdEstadoContacto, 
			System.String Nombre, 
			System.Int32 Orden, 
			System.Boolean Activo);

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForInsert();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForUpdate();

        /// <summary>
        /// 
        /// </summary>
        object[] GetFieldsForDelete();

        /// <summary>
        /// 
        /// </summary>
        void UpdateObjectFromOutputParams(object[] parameters);
    }

    /// <summary>
    /// 
    /// </summary>
    public partial class ContactosEstadosObjectList : ObjectList<ContactosEstadosObject>
    {
    }
}

namespace crmRules.Views
{
    /// <summary>
    /// 
    /// </summary>
    public partial class ContactosEstadosObjectListView
        : ObjectListView<Objects.ContactosEstadosObject>
    {
        /// <summary>
        /// 
        /// </summary>
        public ContactosEstadosObjectListView(Objects.ContactosEstadosObjectList list): base(list)
        {
        }
    }
}


