
//------------------------------------------------------------------------------
// This file was generated by Cooperator Modeler, version 1.3.2.0
// Created: 18/5/2022 - 11:33 a. m.
// This is a partial class file. The other one is ContactosTipoUsuarioMapper.cs
// You should not modifiy this file, please edit the other partial class file.
//------------------------------------------------------------------------------

using System;
using crmRules.Entities;
using crmRules.Objects;
using Cooperator.Framework.Data;
using Cooperator.Framework.Data.Exceptions;
using Cooperator.Framework.Core;
using System.Data.Common;
using System.Reflection;
using System.Web;
using System.Data;

namespace crmRules.Mappers
{

    
    /// <summary>
    /// 
    /// </summary>
    public partial class ContactosTipoUsuarioMapper : BaseGateway<ContactosTipoUsuario, ContactosTipoUsuarioList>, IGenericGateway
    {


        #region "Singleton"

        static ContactosTipoUsuarioMapper _instance;

        private ContactosTipoUsuarioMapper()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public static ContactosTipoUsuarioMapper Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new ContactosTipoUsuarioMapper();
                else {
                    ContactosTipoUsuarioMapper inst = HttpContext.Current.Items["crmRules.ContactosTipoUsuarioMapperSingleton"] as ContactosTipoUsuarioMapper;
                    if (inst == null) {
                        inst = new ContactosTipoUsuarioMapper();
                        HttpContext.Current.Items.Add("crmRules.ContactosTipoUsuarioMapperSingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }


        #endregion

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            
            string[] s ={"IdTipoUsuarioContacto"};
            return s;
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return typeof(ContactosTipoUsuario);
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string TableName
        {
            get { return "ContactosTipoUsuario"; }
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string RuleName
        {
            get {return typeof(ContactosTipoUsuarioMapper).FullName;}
        }


        

        /// <summary>
        /// 
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, ContactosTipoUsuario entity)
        {
            
            IMappeableContactosTipoUsuarioObject ContactosTipoUsuario = (IMappeableContactosTipoUsuarioObject)entity;
            ContactosTipoUsuario.HydrateFields(
            reader.GetInt32(0),
reader.GetString(1),
reader.GetBoolean(2));
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForInsert(ContactosTipoUsuario entity)
        {

            IMappeableContactosTipoUsuarioObject ContactosTipoUsuario = (IMappeableContactosTipoUsuarioObject)entity;
            return ContactosTipoUsuario.GetFieldsForInsert();
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForUpdate(ContactosTipoUsuario entity)
        {

            IMappeableContactosTipoUsuarioObject ContactosTipoUsuario = (IMappeableContactosTipoUsuarioObject)entity;
            return ContactosTipoUsuario.GetFieldsForUpdate();
        }

        /// <summary>
        /// 
        /// </summary>
        protected override object[] GetFieldsForDelete(ContactosTipoUsuario entity)
        {

            IMappeableContactosTipoUsuarioObject ContactosTipoUsuario = (IMappeableContactosTipoUsuarioObject)entity;
            return ContactosTipoUsuario.GetFieldsForDelete();
        }


        /// <summary>
        /// Raised after insert and update
        /// </summary>
        protected override void UpdateObjectFromOutputParams(ContactosTipoUsuario entity, object[] parameters)
        {
            // Update properties from Output parameters
            ((IMappeableContactosTipoUsuarioObject) entity).UpdateObjectFromOutputParams(parameters);
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "coop_";
        }


        


        

        /// <summary>
        /// Complete the aggregations for this entity. 
        /// </summary>
        protected override void CompleteEntity(ContactosTipoUsuario entity)
        {
            
            ((IMappeableContactosTipoUsuario)entity).CompleteEntity();
        }


        # region CRUD Operations
        

        # endregion

        /// <summary>
        /// Delete children for this entity
        /// </summary>
        public void DeleteChildren(DbTransaction transaction, IUniqueIdentifiable entity)
        {
                        
        }


          





        /// <summary>
        /// Get a ContactosTipoUsuario by execute a SQL Query Text
        /// </summary>
        public ContactosTipoUsuario GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a ContactosTipoUsuarioList by execute a SQL Query Text
        /// </summary>
        public ContactosTipoUsuarioList GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }


        /// <summary>
        /// 
        /// </summary>
        public ContactosTipoUsuario GetOne(System.Int32 IdTipoUsuarioContacto)
        {
            return base.GetOne(new ContactosTipoUsuario(IdTipoUsuarioContacto));
        }


        // GetOne By Objects and Params
            


        


        

        /// <summary>
        /// 
        /// </summary>
        public void Delete(System.Int32 IdTipoUsuarioContacto)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "ContactosTipoUsuario_Delete", IdTipoUsuarioContacto);
        }

        /// <summary>
        /// 
        /// </summary>
        public void Delete(DbTransaction transaction, System.Int32 IdTipoUsuarioContacto)
        {
            base.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "ContactosTipoUsuario_Delete", IdTipoUsuarioContacto);
        }


        // Delete By Objects and Params
            



        


        //Database Queries 
        


        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion


    }


}

namespace crmRules.Wrappers
{
    /// <summary>
    /// 
    /// </summary>
    public class ContactosTipoUsuarioMapperWrapper
    {

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            return Instance().GetPKPropertiesNames();
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return Instance().GetMappingType();
        }



        /// <summary>
        /// 
        /// </summary>
        public crmRules.Mappers.ContactosTipoUsuarioMapper Instance()
        {
            return crmRules.Mappers.ContactosTipoUsuarioMapper.Instance(); 
        }
        
        /// <summary>
        /// Get a ContactosTipoUsuarioEntity by calling a Stored Procedure
        /// </summary>
        public Entities.ContactosTipoUsuario GetOne(System.Int32 IdTipoUsuarioContacto) {
            return Instance().GetOne( IdTipoUsuarioContacto);
        }

        // GetBy Objects and Params
            

        

       

        /// <summary>
        /// Delete children for ContactosTipoUsuario
        /// </summary>
        public void DeleteChildren(DbTransaction transaction, ContactosTipoUsuario entity)
        {
            Instance().DeleteChildren(transaction, entity);
        }

        

            

        
        /// <summary>
        /// Delete ContactosTipoUsuario 
        /// </summary>
        public void Delete(System.Int32 IdTipoUsuarioContacto){
            Instance().Delete(IdTipoUsuarioContacto);
        }

        /// <summary>
        /// Delete ContactosTipoUsuario 
        /// </summary>
        public void Delete(Entities.ContactosTipoUsuario entity ){
            Instance().Delete(entity);
        }

        /// <summary>
        /// Save ContactosTipoUsuario  
        /// </summary>
        public void Save(Entities.ContactosTipoUsuario entity){
            Instance().Save(entity);
        }

        /// <summary>
        /// Insert ContactosTipoUsuario 
        /// </summary>
        public void Insert(Entities.ContactosTipoUsuario entity){
            Instance().Insert(entity);
        }

        /// <summary>
        /// GetAll ContactosTipoUsuario 
        /// </summary>
        public Entities.ContactosTipoUsuarioList GetAll(){  
            return Instance().GetAll();
        }

        /// <summary>
        /// Save ContactosTipoUsuario 
        /// </summary>
        public void Save(System.Int32 IdTipoUsuarioContacto, System.String Nombre, System.Boolean Activo){
            Entities.ContactosTipoUsuario entity = Instance().GetOne(IdTipoUsuarioContacto);
            if (entity == null)
                throw new ApplicationException(String.Format("Entity not found. IUniqueIdentifiable Values: {0} = {1}", "IdTipoUsuarioContacto", IdTipoUsuarioContacto));

            entity.Nombre = Nombre;
            entity.Activo = Activo;
            Instance().Save(entity);
        }

        /// <summary>
        /// Insert ContactosTipoUsuario
        /// </summary>
        public void Insert(System.String Nombre, System.Boolean Activo){
            Entities.ContactosTipoUsuario entity = new Entities.ContactosTipoUsuario();

            entity.Nombre = Nombre;
            entity.Activo = Activo;
            Instance().Insert(entity);
        }


        //Database Queries 
        


    }
}





namespace crmRules.Loaders
{

    /// <summary>
    /// 
    /// </summary>
    public partial class ContactosTipoUsuarioLoader<T> : BaseLoader< T, ContactosTipoUsuario, ObjectList<T>>, IGenericGateway where T : ContactosTipoUsuario, new()
    {

        #region "Singleton"

        static ContactosTipoUsuarioLoader<T> _instance;

        private ContactosTipoUsuarioLoader()
        {
        }

        /// <summary>
        /// 
        /// </summary>
        public static ContactosTipoUsuarioLoader<T> Instance() {
            if (_instance == null) {
                if (HttpContext.Current == null) 
                    _instance = new ContactosTipoUsuarioLoader<T>();
                else {
                    ContactosTipoUsuarioLoader<T> inst = HttpContext.Current.Items["crmRules.ContactosTipoUsuarioLoaderSingleton"] as ContactosTipoUsuarioLoader<T>;
                    if (inst == null) {
                        inst = new ContactosTipoUsuarioLoader<T>();
                        HttpContext.Current.Items.Add("crmRules.ContactosTipoUsuarioLoaderSingleton", inst);
                    }
                    return inst;
                }
            }
            return _instance;
        }


        #endregion

        /// <summary>
        /// 
        /// </summary>
        public string[] GetPKPropertiesNames()
        {
            
            string[] s ={"IdTipoUsuarioContacto"};
            return s;
        }
        /// <summary>
        /// 
        /// </summary>
        public Type GetMappingType()
        {
            return typeof(ContactosTipoUsuario);
        }


        /// <summary>
        /// 
        /// </summary>
        protected override string TableName
        {
            get { return "ContactosTipoUsuario"; }
        }

        
        
        /// <summary>
        /// 
        /// </summary>
        protected override void HydrateFields(DbDataReader reader, ContactosTipoUsuario entity)
        {
            
            IMappeableContactosTipoUsuarioObject ContactosTipoUsuario = (IMappeableContactosTipoUsuarioObject)entity;
            ContactosTipoUsuario.HydrateFields(
            reader.GetInt32(0),
reader.GetString(1),
reader.GetBoolean(2));
        }

        /// <summary>
        /// 
        /// </summary>
        protected override string StoredProceduresPrefix()
        {
            return "coop_";
        }


        
    

        

        /// <summary>
        /// Complete the aggregations for this entity. 
        /// </summary>
        protected override void CompleteEntity(T entity)
        {
            
            ((IMappeableContactosTipoUsuario)entity).CompleteEntity();
        }


        



        /// <summary>
        /// Get a ContactosTipoUsuario by execute a SQL Query Text
        /// </summary>
        public T GetOneBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectBySQLText(sqlQueryText);
        }

        /// <summary>
        /// Get a ContactosTipoUsuarioList by execute a SQL Query Text
        /// </summary>
        public ObjectList<T> GetBySQLQuery(string sqlQueryText)
        {
            return base.GetObjectListBySQLText(sqlQueryText);
        }

        /// <summary>
        /// GetOne By Params
        /// </summary>
        public T GetOne(System.Int32 IdTipoUsuarioContacto)
        {
            return base.GetObjectByAnyStoredProcedure(StoredProceduresPrefix() + "ContactosTipoUsuario_GetOne", IdTipoUsuarioContacto);
        }


        // GetOne By Objects and Params
            


        


        

        //Database Queries 
        



        #region IGenericGateway

        object IGenericGateway.GetOne(IUniqueIdentifiable identifier)
        {
            return base.GetOne(identifier);
        }

        object IGenericGateway.GetAll()
        {
            return base.GetAll();
        }

        object IGenericGateway.GetByParent(IUniqueIdentifiable parentEntity)
        {
            return base.GetByParent(parentEntity);
        }

        #endregion

    }
}





